### PR TITLE
prerender: false by default

### PR DESCRIPTION
**Pull request by gfortaine**
add prerender=1 as a parameter to the URL to enable Server-Side Rendering  (cf.  [react_on_rails](https://github.com/shakacode/react_on_rails))

### CODE REVIEW

**Comment by catmando** [comment]
the problem is this is going to be a big semantic change... we have apps in the wild that are assuming prerenender is on.  Perhaps we should do this via a rails config file?  Also thinking of adding as an optional param in the `render_component` method like this:

`render_component "Foo", {param1: 12}, prerender: false, layout: "baz"`

**Comment by gfortaine** [comment]
Totally agree about adding and optional param to set prerender (à la [react_on_rails](https://github.com/shakacode/react_on_rails)). Especially, it completes the #148 suggestion (Customize rendered layout)  (@rdlh and me are in the same team)

**Comment by catmando** [comment]
Okay I can add the prerender option with #148.  How about a default value in initialization?

I think perhaps it should have the following values:  true = always on, false or nil always off, any other symbol means if that symbol is present as a http param then prerendering will be off.

Whatever value is in the config, can be overridden via the call to render_component

**Comment by gfortaine** [comment]
Perfect :smile:

**Comment by catmando** [comment]
and I assume if you want to get on with it, you can know how to monkey patch the current implementation?

**Comment by gfortaine** [comment]
We have too many concerns with this gem (especially, the default routing logic of render_component). Even if we enable Client Only, we don't manage to get react_component right in our view templates (slim). Thus, we will use react_on_rails that is more suited to our needs to ensure a smooth transition of the legacy part of our app.

**Comment by catmando** [comment]
thanks for the feedback...

**Comment by catmando** [comment]
Prerendering is now controllable at three levels:

1. in the rails hyperloop initializer you can say:   
    ```ruby
    Hyperloop.configuration do |config|
      config.prerendering = :off # :on by default
    end
    ```

2. in a route you can override the config setting by setting a default for `hyperloop_prerendering`:    
    ```ruby
    get '/some_page', to: 'hyperloop#some_page', defaults: {hyperloop_prerendering: :off} # or :on
    ```
    This allows you to override the prerendering option for specific pages.  For example the application may have prererendering off by default (via the config setting) but you can still turn it on for a specific page.

3. You can override the route, and config setting using the `hyperloop-prerendering` query param:    
    ```text
    http://localhost:3000/my_hyper_app/some_page?hyperloop-prerendering=off
    ```  
    This is useful for development and testing  
    **NOTE:  in the route you say hyperloop_prererendering but in the query string its hyperloop-prerendering (underscore vs. dash).  This is because of rails security protection when using defaults.**

**Pull request closed without merging**
