### PR TITLE
Added to_key methods and tests

### PR DESCRIPTION
**Pull request by Donnadieu**

### CODE REVIEW

**Review by catmando — APPROVED** [review]
nice job...
I will fix this but be careful to remove "pause" from tests

**Comment by Donnadieu** [comment]
Thank you Mitch sorry about that

**Comment by sfcgeorge** [comment]
Using this now, works nicely :)

In future could add this so that the same OOID will be seen in Components and Hyper Mesh (note using the backing_record OOID)

```ruby
# don't think this is the best class to put it in,
# should probably be client only in an RR class 
class ActiveRecord::Base
  def to_key
    backing_record.object_id
  end
end
```

E.g. you use it in a component with a record `Foo(id: "foo-#{foo.to_key}")`

**Comment by catmando** [comment]
@sfcgeorge this has been closed by https://github.com/ruby-hyperloop/hyper-mesh/issues/61 its currently on edge

**Pull request merged**
