### PR TITLE
Hotfix for 0-8-stable

### PR DESCRIPTION
**Pull request by zetachang**
Some opal tests are broken after introducing baf71b4. 

The reason is that it introduce changes to **component.rb** & **api.rb** which comment out the `render` method check and use `respond_to?` instead of `method_defined?`. 
- api.rb (https://github.com/reactrb/reactrb/blob/baf71b4d4399398b87410ddb22e9ae43fdb4236f/lib/react/api.rb#L40)
- component.rb (https://github.com/reactrb/reactrb/blob/baf71b4d4399398b87410ddb22e9ae43fdb4236f/lib/react/component.rb#L116)

@catmando, is there any intent on doing this?

### CODE REVIEW

**Comment by zetachang** [comment]
The test is failed because jRuby shipped with bundler v1.7.12 (other rubies used v1.7.6) which resolve opal v0.10 as dependency rather than v0.8. And somehow jRuby is not compatible with opal 0.10

```
SyntaxError: /home/travis/.rvm/gems/jruby-1.7.19-d19/gems/opal-0.10.1/lib/opal/nodes/def.rb:83: invalid multibyte char (US-ASCII)
```

[Update] Just to clarify.. I am talking about the CI test result. The tests are still passed on MRI and phantomjs

**Comment by catmando** [comment]
need help understanding all this... sorry

**Comment by zetachang** [comment]
The PR is actually the commit baf71b4d4399398b87410ddb22e9ae43fdb4236f without those two files mentioned and including those skipped tests.

**Comment by catmando** [comment]
do you want me to approve this?  I don't think I need to if you are okay with it.

**Comment by zetachang** [comment]
Just need you to double check given that this revert some changes you make.
If you are fine with it, I will just go for it.

Mitch VanDuyn notifications@github.com 於 2016年9月10日週六 上午9:14 寫道：

**Pull request merged**
